CREATE TABLE [dbo].[UserRole]
(
    [UserId] UNIQUEIDENTIFIER CONSTRAINT [FK_UserRole_User] FOREIGN KEY REFERENCES [User](Id) ON DELETE CASCADE,
    [RoleId] INT CONSTRAINT [FK_UserRole_Role] FOREIGN KEY REFERENCES [Role](Id) ON DELETE CASCADE
);